trigger:
  branches:
    include:
      - main
  paths:
    include:
      - %MODULE_NAME%/content/*

pool:
  vmImage: windows-latest

steps:
  - powershell: |
      Compress-Archive `
        -Path "%MODULE_NAME%/content" `
        -DestinationPath "$(Pipeline.Workspace)/data.zip"
    name: PackData
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Pipeline.Workspace)/data.zip"
      artifact: "data"
      publishLocation: "pipeline"
