trigger:
  branches:
    include:
      - main
  paths:
    include:
      - %MODULE_NAME%/content/*

pool:
  vmImage: windows-latest

steps:
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "%MODULE_NAME%/content"
      artifact: "data"
      publishLocation: "pipeline"
