parameters:
  EnvironmentName: ""
  Type: "Managed"

jobs:
- deployment: ${{ parameters.EnvironmentName }}
  variables:
  - group: Credentials
  - group: ${{ parameters.EnvironmentName }}
  - group: ConnectionString
  environment: ${{ parameters.EnvironmentName }}
  pool:
    vmImage: windows-latest
  strategy:
    runOnce:
      deploy:
        steps:
#        - download: BuildConfigurationModularization
#          name: DownloadConfigurationModularization
        - pwsh: mkdir "$(Pipeline.Workspace)/logs"
          name: CreateLogsDirectory
        - powershell: |
            Install-Module `
              -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell `
              -Force
            Install-Module `
              -Name Microsoft.Xrm.Tooling.ConfigurationMigration `
              -Force
#        - task: MSCRMToolInstaller@12
#        - task: MSCRMImportSolution@12
#          inputs:
#            crmConnectionString: '$(ConnectionString)'
#            solutionFile: '$(Pipeline.Workspace)/BuildConfigurationModularization/packed-solution/ConfigurationModularization_managed.zip'
#            logsDirectory: '$(Pipeline.Workspace)/logs'
#            crmConnectionTimeout: '600'
#          name: ImportConfigurationModularization
%MODULES%
        - task: PublishPipelineArtifact@1
          condition: always()
          inputs:
            targetPath: "$(Pipeline.Workspace)/logs"
            artifact: "logs"
            publishLocation: "pipeline"
