trigger: none

resources:
  pipelines:
  - pipeline: BuildConfigurationModularization
    branch: main
    source: BuildConfigurationModularization
    trigger:
      branches:
        include:
        - main
%MODULES%

jobs:
  - template: templates/deploy.yml
    parameters:
      EnvironmentName: "Development"
      Type: "Unmanaged"
